name: 'DatoCMS to Markdown'
description: 'Easily embed DatoCMS contents into Markdown.'
inputs:
  datocms-token: # token of datoCms
    description: 'Token of your datoCms site.enter your project administrative area (ie. http://your-project.admin.datocms.com) and go to the  Settings > API Tokens section.'
    required: true
    default: 'OOXXOOXX'
  datocms-filter-model-ids:
    description: 'Module IDs for generate contents, spilit by `,`. (https://www.datocms.com/docs/content-management-api/resources/item-type)'
    required: false
    default: 'blog'
  datocms-post-url:
    description: 'Url to your post. (ie. `https://buzhou.top/blogs/{{slug}}`)'
    required: true
    default: 'http://localhost/blogs/{{slug}}'
  markdown-file:
    description: 'Which file to write'
    required: true
    default: 'README.md'
  template-variable:
    description: 'Where to inject generated content'
    required: true
    default: '{{datocms_content}}'
runs:
  using: 'node12'
  main: 'dist/index.js'
