name: 'DatoCMS to Markdown'
description: 'Easily embed DatoCMS contents into Markdown.'
inputs:
  datocms-token: # token of datoCms
    description: 'Token of your datoCms site.enter your project administrative area (ie. http://your-project.admin.datocms.com) and go to the  Settings > API Tokens section.'
    required: true
    default: 'OOXXOOXX'
  datocms-filter-model-ids:
    description: 'Module IDs for generate contents, spilit by `,`. (https://www.datocms.com/docs/content-management-api/resources/item-type)'
    required: false
    default: 'blog'
  datocms-record-template:
    description: 'template to generate each line.'
    required: true
    default: '- [{{title}}](http://localhost/blogs/{{slug}})'
  datocms-putput-file:
    description: 'Which file to write'
    default: 'README.md'
  datocms-template-file:
    description: 'Template for generate output'
    deafult: 'README.template.md'
  datocms-template-variable:
    description: 'Where to inject generated content'
    default: '{{datocms_content}}'
runs:
  using: 'node12'
  main: 'dist/index.js'
