name: 'DatoCMS to Markdown'
description: 'Easily embed DatoCMS contents into Markdown.'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  datocms-token: # token of datoCms
    description: 'Token of your datoCms site.enter your project administrative area (ie. http://your-project.admin.datocms.com) and go to the  Settings > API Tokens section.'
    required: true
    default: 'OOXXOOXX'
  datocms-filter-model-ids:
    description: 'Module IDs for generate contents, spilit by `,`. (https://www.datocms.com/docs/content-management-api/resources/item-type)'
    required: false
    default: 'blog'
  datocms-template-file:
    description: 'Template for generate output'
    default: 'README.template.md'
  datocms-output-file:
    description: 'Which file to write'
    default: 'README.md'
runs:
  using: 'node12'
  main: 'dist/index.js'
